spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: _sYf95C6tUK2IfMJsmkO
            client-secret: NcA5IUn2Yi
            scope:
              - name
              - email
              - nickname
              - gender
              - birth
              - number
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id:
            redirect-uri: http://localhost:8778/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            client-authentication-method: POST

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secretkey: ACCESS_TOKEN_SECRET=MheAhAP2Wx4PPQuiBSzV7iLHFfkyhb4N7zv1t+8r2Ewf1NTT
  accessTokenExpiration: 86400000
  refreshTokenExpiration: 604800000