spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

logging:
  slack:
    webhook-uri: http://localhost:8080/log-callback
  config: classpath:logback-spring.xml

jwt:
  secretkey: MheAhAP2Wx4PPQuiBSzV7iLHFfkyhb4N7zv1t+8r2Ewf1NTT
  accessTokenExpiration: 86400000
  refreshTokenExpiration: 604800000