spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234

logging:
  slack:
    webhook-uri: http://localhost:8080/log-callback
  config: classpath:logback-spring.xml

jwt:
  secretkey: ${SECRETKEY}
  accessTokenExpiration: 86400000
  refreshTokenExpiration: 604800000


cloud:
  aws:
    s3:
      bucket: uglypotato-bucket
    credentials:
      access-key: ${AWS_ACCESSKEY}
      secret-key: ${AWS_SECRETKEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

email:
  id: uglypotato5913@gmail.com
  password: ldushxapuefwqfxn
  expiration: 300000

imp:
  api-key: ${API_KEY}
  api-secret-key: ${API_SECRET_KEY}