name: github-actions-with-AWS-CodeDeploy

# 실행 시기
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Chekcout Main Branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant Permission Gradlew
      run: chmod +x gradlew
      shell: bash
    
    - name: Build Gradle
      run: ./gradlew build
      shell: bash

    - name: Make zip file
      run: zip -r ./UGLY_POTATO_BACKEND_ACTION.zip .
      shell: bash
